local addonName, NS = ...

NS.ENCHANT_DATA = {
    [3817] = { name = "Arcanum of Blissful Mending", slot = "head" },
    [3818] = { name = "Arcanum of Burning Mysteries", slot = "head" },
    [3819] = { name = "Arcanum of the Stalwart Protector", slot = "head" },
    [3820] = { name = "Arcanum of Torment", slot = "head" },
    [3842] = { name = "Arcanum of the Savage Gladiator", slot = "head" },

    [3806] = { name = "Master's Inscription of the Axe", slot = "shoulder" },
    [3807] = { name = "Master's Inscription of the Crag", slot = "shoulder" },
    [3808] = { name = "Master's Inscription of the Pinnacle", slot = "shoulder" },
    [3809] = { name = "Master's Inscription of the Storm", slot = "shoulder" },
    [3810] = { name = "Greater Inscription of the Axe", slot = "shoulder" },
    [3811] = { name = "Greater Inscription of the Crag", slot = "shoulder" },
    [3812] = { name = "Greater Inscription of the Pinnacle", slot = "shoulder" },
    [3813] = { name = "Greater Inscription of the Storm", slot = "shoulder" },

    [3831] = { name = "Greater Speed", slot = "back" },
    [3294] = { name = "Superior Agility", slot = "back" },
    [3296] = { name = "Superior Dodge", slot = "back" },
    [3825] = { name = "Speed", slot = "back" },
    [3243] = { name = "Lightweave Embroidery", slot = "back" },
    [1099] = { name = "Major Agility", slot = "back" },
    [3728] = { name = "Darkglow Embroidery", slot = "back" },
    [3730] = { name = "Swordguard Embroidery", slot = "back" },

    [3832] = { name = "Powerful Stats", slot = "chest" },
    [3297] = { name = "Super Health", slot = "chest" },
    [3252] = { name = "Super Stats", slot = "chest" },
    [3233] = { name = "Exceptional Mana", slot = "chest" },
    [3245] = { name = "Exceptional Resilience", slot = "chest" },

    [3845] = { name = "Greater Assault", slot = "wrist" },
    [3850] = { name = "Major Stamina", slot = "wrist" },
    [3848] = { name = "Greater Spellpower", slot = "wrist" },
    [3256] = { name = "Superior Spellpower", slot = "wrist" },
    [2661] = { name = "Greater Stats", slot = "wrist" },
    [2650] = { name = "Exceptional Intellect", slot = "wrist" },

    [3829] = { name = "Greater Assault", slot = "hands" },
    [3253] = { name = "Armsman", slot = "hands" },
    [3234] = { name = "Precision", slot = "hands" },
    [3238] = { name = "Gatherer", slot = "hands" },
    [3231] = { name = "Major Agility", slot = "hands" },
    [3222] = { name = "Greater Agility", slot = "hands" },
    [3860] = { name = "Crusher", slot = "hands" },

    [3853] = { name = "Frosthide Leg Armor", slot = "legs" },
    [3822] = { name = "Icescale Leg Armor", slot = "legs" },
    [3852] = { name = "Jormungar Leg Armor", slot = "legs" },
    [3325] = { name = "Nerubian Leg Armor", slot = "legs" },
    [3326] = { name = "Wyrmscale Leg Armor", slot = "legs" },

    [3826] = { name = "Icewalker", slot = "feet" },
    [3232] = { name = "Tuskarr's Vitality", slot = "feet" },
    [3824] = { name = "Assault", slot = "feet" },
    [3606] = { name = "Nitro Boosts", slot = "feet" },
    [3244] = { name = "Greater Vitality", slot = "feet" },
    [1075] = { name = "Greater Fortitude", slot = "feet" },
    [3847] = { name = "Greater Assault", slot = "feet" },

    [3839] = { name = "Greater Assault", slot = "finger" },
    [3840] = { name = "Greater Spellpower", slot = "finger" },
    [3791] = { name = "Assault", slot = "finger" },
    [3790] = { name = "Spellpower", slot = "finger" },

    [3827] = { name = "Berserking", slot = "weapon" },
    [3828] = { name = "Black Magic", slot = "weapon" },
    [3830] = { name = "Accuracy", slot = "weapon" },
    [3833] = { name = "Superior Potency", slot = "weapon" },
    [3834] = { name = "Mighty Spellpower", slot = "weapon" },
    [3241] = { name = "Lifeward", slot = "weapon" },
    [3239] = { name = "Icebreaker", slot = "weapon" },
    [3251] = { name = "Scourgebane", slot = "weapon" },
    [3365] = { name = "Rune of the Fallen Crusader", slot = "weapon" },
    [3366] = { name = "Rune of Lichbane", slot = "weapon" },
    [3367] = { name = "Rune of Spellshattering", slot = "weapon" },
    [3368] = { name = "Rune of the Nerubian Carapace", slot = "weapon" },
    [3369] = { name = "Rune of Spellbreaking", slot = "weapon" },
    [3370] = { name = "Rune of Swordbreaking", slot = "weapon" },
    [3594] = { name = "Rune of the Stoneskin Gargoyle", slot = "weapon" },
    [3595] = { name = "Rune of Swordshattering", slot = "weapon" },
    [3843] = { name = "Massacre", slot = "weapon" },
    [3844] = { name = "Greater Savagery", slot = "weapon" },
    [3846] = { name = "Major Healing", slot = "weapon" },

    [3849] = { name = "Greater Intellect", slot = "shield" },
    [3229] = { name = "Resilience", slot = "shield" },
    [2655] = { name = "Shield Block", slot = "shield" },
    [1952] = { name = "Major Stamina", slot = "shield" },
}

NS.ENCHANTABLE_SLOTS = {
    [1] = true,
    [3] = true,
    [5] = true,
    [6] = true,
    [7] = true,
    [8] = true,
    [9] = true,
    [10] = true,
    [11] = true,
    [12] = true,
    [15] = true,
    [16] = true,
    [17] = true,
    [18] = true,
}
